### ISSUE TITLE
Add Wallpaper: Fedora 34 default wallpaper

### ISSUE THREAD

**Issue by aerfanr** [karmanyaahm/awesome-plasma5-dynamic-wallpapers#4]
Here is the repo: https://github.com/aerfanr/fedora-34-kde-dynamic-wallpaper
artwork by Fedora Design Team

**Comment by zzag** [comment]
Can you please create a PR linking your repo?

**Comment by karmanyaahm** [comment]
I missed this issue I'll add it tonight

**Comment by karmanyaahm** [comment]
Commit 7099962
